import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Helvetica',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
    borderBottom: '1px solid #E5E7EB',
    paddingBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#111827',
  },
  invoiceNumber: {
    fontSize: 12,
    color: '#6B7280',
  },
  clientSection: {
    marginBottom: 30,
  },
  clientName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 4,
  },
  clientDetail: {
    fontSize: 10,
    color: '#6B7280',
    marginBottom: 2,
  },
  table: {
    display: 'table',
    width: 'auto',
    marginBottom: 20,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    paddingVertical: 8,
  },
  tableHeader: {
    backgroundColor: '#F9FAFB',
    paddingVertical: 10,
    fontWeight: 'bold',
  },
  tableCol1: { width: '50%' },
  tableCol2: { width: '20%', textAlign: 'right' },
  tableCol3: { width: '15%', textAlign: 'right' },
  tableCol4: { width: '15%', textAlign: 'right' },
  totalSection: {
    marginTop: 20,
    borderTopWidth: 2,
    borderTopColor: '#111827',
    paddingTop: 10,
    alignItems: 'flex-end',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 4,
  },
  totalLabel: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#111827',
  },
  totalValue: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#111827',
    width: 100,
    textAlign: 'right',
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: {
    fontSize: 8,
    color: '#6B7280',
  },
});

interface InvoiceData {
  invoiceNumber: string;
  createdAt: Date;
  customerName: string;
  customerPhone?: string | null;
  customerEmail?: string | null;
  items: Array<{ description: string; quantity: number; price: number }>;
  total: number;
  currency: string;
  bankName?: string | null;
  bankAccount?: string | null;
  bankAccountName?: string | null;
}

export const MinimalTemplate = ({ data }: { data: InvoiceData }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <View>
          <Text style={styles.title}>INVOICE</Text>
          <Text style={styles.invoiceNumber}>#{data.invoiceNumber}</Text>
        </View>
        <View>
          <Text style={styles.invoiceNumber}>Date: {new Date(data.createdAt).toLocaleDateString()}</Text>
        </View>
      </View>

      <View style={styles.clientSection}>
        <Text style={styles.clientName}>Bill To:</Text>
        <Text style={styles.clientName}>{data.customerName}</Text>
        {data.customerEmail && <Text style={styles.clientDetail}>{data.customerEmail}</Text>}
        {data.customerPhone && <Text style={styles.clientDetail}>{data.customerPhone}</Text>}
      </View>

      <View style={styles.table}>
        <View style={[styles.tableRow, styles.tableHeader]}>
          <Text style={styles.tableCol1}>Description</Text>
          <Text style={styles.tableCol2}>Qty</Text>
          <Text style={styles.tableCol3}>Price</Text>
          <Text style={styles.tableCol4}>Total</Text>
        </View>
        {data.items.map((item, index) => (
          <View key={index} style={styles.tableRow}>
            <Text style={styles.tableCol1}>{item.description}</Text>
            <Text style={styles.tableCol2}>{item.quantity}</Text>
            <Text style={styles.tableCol3}>{data.currency} {item.price.toFixed(2)}</Text>
            <Text style={styles.tableCol4}>{data.currency} {(item.quantity * item.price).toFixed(2)}</Text>
          </View>
        ))}
      </View>

      <View style={styles.totalSection}>
        <View style={styles.totalRow}>
          <Text style={styles.totalLabel}>Total:</Text>
          <Text style={styles.totalValue}>{data.currency} {data.total.toFixed(2)}</Text>
        </View>
      </View>

      {data.bankName && (
        <View style={{ marginTop: 20, paddingTop: 10, borderTopWidth: 1, borderTopColor: '#E5E7EB' }}>
          <Text style={{ fontSize: 10, color: '#6B7280', marginBottom: 2 }}>Bank: {data.bankName}</Text>
          {data.bankAccountName && <Text style={{ fontSize: 10, color: '#6B7280', marginBottom: 2 }}>Account: {data.bankAccountName}</Text>}
          {data.bankAccount && <Text style={{ fontSize: 10, color: '#6B7280' }}>Account #: {data.bankAccount}</Text>}
        </View>
      )}

      <View style={styles.footer}>
        <Text style={styles.footerText}>Thank you for your business!</Text>
        <Text style={styles.footerText}>Generated by Fatura.one</Text>
      </View>
    </Page>
  </Document>
);