import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { prisma } from "@/lib/prisma/client";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { invoiceId, email } = body;

    if (!invoiceId || !email) {
      return NextResponse.json(
        { error: "Invoice ID and email required" },
        { status: 400 }
      );
    }

    // Get invoice data
    const invoice = await prisma.invoice.findUnique({
      where: { id: invoiceId },
      include: { items: true },
    });

    if (!invoice) {
      return NextResponse.json(
        { error: "Invoice not found" },
        { status: 404 }
      );
    }

    // Build email HTML (same as before)
    const itemsHtml = invoice.items.map(item => `
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${item.description}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: center;">${item.quantity}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: right;">${item.price.toFixed(2)}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: right;">${(item.quantity * item.price).toFixed(2)}</td>
      </tr>
    `).join('');

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { border-bottom: 2px solid #2563eb; padding-bottom: 10px; margin-bottom: 20px; }
          .header h1 { color: #2563eb; margin: 0; }
          .invoice-number { color: #6b7280; font-size: 14px; }
          .total { font-size: 20px; font-weight: bold; color: #2563eb; }
          .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #6b7280; text-align: center; }
          .btn { display: inline-block; background: #2563eb; color: white; padding: 10px 20px; text-decoration: none; border-radius: 6px; }
          .signup-box { background: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0; text-align: center; }
          table { width: 100%; border-collapse: collapse; }
          th { text-align: left; padding: 8px; background: #f3f4f6; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Fatura.one</h1>
          <p class="invoice-number">Invoice #${invoice.invoiceNumber}</p>
        </div>

        <p>Hi ${invoice.customerName},</p>
        <p>Your invoice is ready! Here are the details:</p>

        <h3>Bill to:</h3>
        <p><strong>${invoice.customerName}</strong></p>
        ${invoice.customerEmail ? `<p>${invoice.customerEmail}</p>` : ''}
        ${invoice.customerPhone ? `<p>${invoice.customerPhone}</p>` : ''}

        <h3>Invoice Items:</h3>
        <table>
          <thead>
            <tr>
              <th>Description</th>
              <th style="text-align: center;">Qty</th>
              <th style="text-align: right;">Price</th>
              <th style="text-align: right;">Total</th>
            </tr>
          </thead>
          <tbody>
            ${itemsHtml}
          </tbody>
          <tfoot>
            <tr>
              <td colspan="3" style="padding: 8px; text-align: right; font-weight: bold;">Total:</td>
              <td style="padding: 8px; text-align: right; font-weight: bold; font-size: 18px; color: #2563eb;">
                ${invoice.total.toFixed(2)} ${invoice.currency}
              </td>
            </tr>
          </tfoot>
        </table>

        <div class="signup-box">
          <h3>✨ Save & Manage Your Invoices</h3>
          <p>Create a free account to:</p>
          <ul style="text-align: left; display: inline-block;">
            <li>Save all your invoices</li>
            <li>Track views and payments</li>
            <li>Send invoices to clients</li>
            <li>Get 2 free invoices per month</li>
          </ul>
          <br/>
          <a href="${process.env.NEXTAUTH_URL}/auth/signup?email=${email}" class="btn">
            Create Free Account
          </a>
        </div>

        <div style="text-align: center; margin: 20px 0;">
          <a href="${process.env.NEXTAUTH_URL}/invoice/${invoice.id}/view" class="btn">
            View Invoice Online
          </a>
        </div>

        <div class="footer">
          <p>This invoice was generated by <a href="${process.env.NEXTAUTH_URL}" style="color: #2563eb;">Fatura.one</a></p>
        </div>
      </body>
      </html>
    `;

    // Send email
    const { data, error } = await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL || "Fatura <noreply@fatura.one>",
      to: [email],
      subject: `Your Invoice ${invoice.invoiceNumber} from Fatura.one`,
      html: html,
    });

    if (error) {
      console.error("Resend error:", error);
      return NextResponse.json(
        { error: "Failed to send email" },
        { status: 500 }
      );
    }

    // Update invoice with guest email
    await prisma.invoice.update({
      where: { id: invoiceId },
      data: { 
        customerEmail: email,
        status: "SENT",
      },
    });

    return NextResponse.json({
      success: true,
      message: "Invoice sent to your email!",
      id: data?.id,
    });
  } catch (error) {
    console.error("Email error:", error);
    return NextResponse.json(
      { error: "Failed to send email" },
      { status: 500 }
    );
  }
}