import { PDFDocument, rgb } from 'pdf-lib';

export interface InvoiceData {
  invoiceNumber: string;
  createdAt: Date;
  customerName: string;
  customerPhone?: string | null;
  customerEmail?: string | null;
  items: Array<{
    description: string;
    quantity: number;
    price: number;
  }>;
  total: number;
  currency: string;
  bankName?: string | null;
  bankAccount?: string | null;
  bankAccountName?: string | null;
}

export async function generatePDF(data: InvoiceData): Promise<Buffer> {
  try {
    // Create a new PDF document
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 842]); // A4 size
    
    // Get the standard font - using built-in fonts to avoid issues
    const font = await pdfDoc.embedStandardFont('Helvetica');
    const fontBold = await pdfDoc.embedStandardFont('Helvetica-Bold');
    
    const { width, height } = page.getSize();
    let y = height - 50;
    
    // Helper function to draw text
    const drawText = (text: string, x: number, yPos: number, size: number = 12, bold: boolean = false) => {
      const fontToUse = bold ? fontBold : font;
      page.drawText(text, {
        x,
        y: yPos,
        size,
        font: fontToUse,
        color: rgb(0, 0, 0),
      });
    };
    
    // Title
    drawText('INVOICE', 50, y, 24, true);
    y -= 30;
    
    // Invoice Number
    drawText(`Invoice #: ${data.invoiceNumber}`, 50, y, 12, true);
    y -= 20;
    
    // Date
    drawText(`Date: ${new Date(data.createdAt).toLocaleDateString()}`, 50, y, 12);
    y -= 30;
    
    // Customer Section
    drawText('Bill To:', 50, y, 14, true);
    y -= 20;
    drawText(data.customerName, 50, y, 12);
    y -= 16;
    if (data.customerEmail) {
      drawText(`Email: ${data.customerEmail}`, 50, y, 10);
      y -= 16;
    }
    if (data.customerPhone) {
      drawText(`Phone: ${data.customerPhone}`, 50, y, 10);
      y -= 16;
    }
    y -= 20;
    
    // Table Header
    drawText('Description', 50, y, 12, true);
    drawText('Qty', 350, y, 12, true);
    drawText('Price', 420, y, 12, true);
    drawText('Total', 490, y, 12, true);
    y -= 10;
    
    // Line
    page.drawLine({
      start: { x: 50, y: y },
      end: { x: 550, y: y },
      thickness: 1,
      color: rgb(0.5, 0.5, 0.5),
    });
    y -= 15;
    
    // Table Rows
    data.items.forEach((item) => {
      const total = item.quantity * item.price;
      drawText(item.description, 50, y, 10);
      drawText(item.quantity.toString(), 350, y, 10);
      drawText(`${data.currency} ${item.price.toFixed(2)}`, 420, y, 10);
      drawText(`${data.currency} ${total.toFixed(2)}`, 490, y, 10);
      y -= 20;
    });
    
    y -= 10;
    
    // Total
    page.drawLine({
      start: { x: 350, y: y },
      end: { x: 550, y: y },
      thickness: 2,
      color: rgb(0.2, 0.2, 0.2),
    });
    y -= 15;
    
    drawText(`TOTAL: ${data.currency} ${data.total.toFixed(2)}`, 400, y, 16, true);
    y -= 40;
    
    // Bank Details
    if (data.bankName) {
      drawText('Payment Information:', 50, y, 12, true);
      y -= 20;
      drawText(`Bank: ${data.bankName}`, 50, y, 10);
      y -= 16;
      if (data.bankAccountName) {
        drawText(`Account Name: ${data.bankAccountName}`, 50, y, 10);
        y -= 16;
      }
      if (data.bankAccount) {
        drawText(`Account Number: ${data.bankAccount}`, 50, y, 10);
        y -= 16;
      }
    }
    
    // Footer
    drawText('Thank you for your business!', 50, 50, 10);
    drawText('Generated by Fatura.one', 450, 50, 8);
    
    // Save PDF
    const pdfBytes = await pdfDoc.save();
    return Buffer.from(pdfBytes);
  } catch (error) {
    console.error('PDF generation error:', error);
    throw error;
  }
}